- name: Install Docker
  hosts: all
  roles:
    - role: docker
      become: true

- name: Javascript web app deployment
  hosts: all
  roles: 
  - role: web_app
    become: true
    vars:
      app_name: "ubuntu-js-web-app"
      app_port: 3000