- name: Check Docker Compose File Presence
  stat:
    path: "{{ app_dir }}/docker-compose.yml"
  register: present_dir
  when: web_app_full_wipe | bool

- name: Execute Full Wipe
  block:
    - name: Remove Docker Environment
      command: docker-compose down -v
      args:
        chdir: "{{ app_dir }}"

    - name: Prune Docker Networks and Images
      block:
        - command: docker network prune -f
        - command: docker image prune -a -f

    - name: Delete Configuration Files
      block:
        - file:
            path: "{{ app_dir }}/docker-compose.yml"
            state: absent
      tags:
        - wipe

  when: web_app_full_wipe | bool and present_dir.stat.exists
  tags:
    - wipe
