apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-app-deployment
  labels:
    app: js-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: js-app
  template:
    metadata:
      labels:
        app: js-app
    spec:
      containers:
        - name: js-app
          image: ghadeero/js-web-app
          ports:
            - containerPort: 3000
