name: app python

on: [push]

jobs:
  build-app-pipeline:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"
          cache: "pip"
          cache-dependency-path: "app_python/requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt

      - name: Run linter
        working-directory: app_python
        run: |
          pip install flake8
          flake8

      - name: Run unit tests
        working-directory: app_python
        run: python -m unittest

  snyk:
    needs: build-app-pipeline
    timeout-minutes: 1

    name: Run Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Snyk vulnerability scan
        uses: snyk/actions/python-3.10@master
        with:
          args: --skip-unresolved app_python/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    docker-build:
    runs-on: ubuntu-latest

    needs:
      - build
      - security
    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build  Docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/python-web-app:latest ./app_python

      - name: Push Docker image
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/python-web-app:latest